name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/nikos-el/supervisor/amd64-hassio-supervisor:latest
          registry: ghcr.io
          build-args: |
            BUILD_FROM="ubuntu:18.04"
            CAS_VERSION="1.0.2"
            SUPERVISOR_VERSION="2023.03.3"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
