name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/nikos-el/supervisor/aarch64-hassio-supervisor:latest
          build-args: |
            BUILD_FROM="ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.14"
            CAS_VERSION="1.0.2"
            SUPERVISOR_VERSION="2023.03.3"
